toc:
  - title: Introduction
    subfolderitems:
      - page: Getting started
        url: /get-started
      - page: Overview
        url: /overview
  - title: Build a basic subscription service
    subfolderitems:
      - page: Model your business
        url: /model
      - page: Create the customer object
        url: /customer
      - page: Collect payment information
        url: /payment
      - page: Create the subscription object
        url: /examples
  - title: Test your integration
    subfolder items:
      - page: Set up webhooks
        url: /webhooks
      - page: Testing 
        url: /testing
  - title: Add functionality
    subfolderitems:
      - page: Customer authentication
        url: /authentication
      - page: Display subscription details
        url: /details
      - page: Display payment method
        url: /display-method
